### ISSUE TITLE
Problems when running evaluation

### ISSUE THREAD

**Issue by JIANG-CX** [ChenYutongTHU/SplatFormer#1]
Hi, I noticed that there is no file named "train-on-objaverse_test.sh" in the "scripts" folder; there is only "train-on-objaverse_inference.sh." However, when I run "train-on-objaverse_inference.sh," I receive an error message stating "[Errno 2] No such file or directory: 'test-set/realOOD_v2/nerfstudio'." I cannot find the "realOOD_v2" folder in the provided test set. Thank you.

**Comment by ChenYutongTHU** [comment]
Hi, thanks for your interest.

I'm sorry for the naming issue. I haven't updated the Readme and [objaverse.gin](https://github.com/ChenYutongTHU/SplatFormer/blob/main/configs/dataset/objaverse.gin).
Please run train-on-objaverse_inference.sh and realOOD_v2 is realOOD in the provided test set.

**Comment by JIANG-CX** [comment]
Thank you for your response. I would like to know if it is possible to view the enhanced rendering results from various directions in a viewer similar to that in 3DGS. Thanks.

**Comment by ChenYutongTHU** [comment]
Yes. It is possible. 
Our network's output can be converted to a format which could be viewed by SIBR viewer used in the original [3DGS](https://github.com/graphdeco-inria/gaussian-splatting). Yet now it will take me some time to incorporate this feature into our code.

Our test set contains camera poses from various elevation degrees. You can also modify this line to see renderings from more viewpoints.
https://github.com/ChenYutongTHU/SplatFormer/blob/2e4193302ad6947c8fdc44d061e2238b83f58e28/dataset/GS.py#L221

**Comment by JIANG-CX** [comment]
Ok, thanks for your reply. Great work! I am looking forward to this feature.
