### ISSUE TITLE
About the training dataset

### ISSUE THREAD

**Issue by Whiteneko24** [ChenYutongTHU/SplatFormer#3]
Great work! I wonder if the complete training data will be released in the future?

**Comment by ChenYutongTHU** [comment]
Thanks for your interest.
You can use our released [scripts](https://github.com/ChenYutongTHU/SplatFormer_DataGenerator/tree/1c20e0e8be250aa5ccaf51680ff4e84199c68d54) to download 3D scenes, render them, and generate the input 3DGSs.  You can follow the [README](https://github.com/ChenYutongTHU/SplatFormer_DataGenerator/blob/1c20e0e8be250aa5ccaf51680ff4e84199c68d54/README.md) to reproduce our training data.

Now we do not plan to upload the large-sized complete training data. Using the generator scripts can be equally convenient yet more controllable and transparent. Thanks for your understanding.

**Comment by Whiteneko24** [comment]
Completely understand, thanks for your work tho ; )
