### ISSUE TITLE
Release SplatFormer on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [ChenYutongTHU/SplatFormer#4]
Hello @ChenYutongTHU and team 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered on PapersWithCode and indexed your paper here: https://huggingface.co/papers/2411.06390. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the models you've pre-trained on https://huggingface.co/models? I see you're using Google Drive for it. Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

Let me know if you're interested/need any guidance.

Kind regards,

Niels

**Comment by ChenYutongTHU** [comment]
Dear Niels and the HuggingFace 🤗 Team,

Thank you so much for your kind invitation and continuing contributions to the open-source community.

We think it’s a fantastic idea to host our models and dataset on HuggingFace. We will follow your instructions and make them available online soon.

Once again, thank you and we look forward to future collaboration.

Best regards,
Yutong
