### ISSUE TITLE
Can't not eval on real dataset!

### ISSUE THREAD

**Issue by ryan-utopia** [ChenYutongTHU/SplatFormer#7]
When running `sh scripts/train-on-objaverse_inference.sh `

GSO and objaverse work well, but when it comes to real, this happened:

```bash
File "/home/ryan/SplatFormer/utils/metrics.py", line 65, in sum
if max([x.dim() for x in self.results[metric]]) == 0:
ValueError: max() arg is an empty sequence
```

![image](https://github.com/user-attachments/assets/11c74043-b91a-4f03-ac8b-711cab5c024f)

if I want to evaluate my own dataset, what i should do next, could u provide some tips?

**Comment by ChenYutongTHU** [comment]
Hello,

Thanks for this issue. 

First, regarding the inference on our real-world dataset, could you please check if there is any output images under the directory outputs/objaverse_splatformer/test/real, and the real-world dataset is placed under test-set/realOOD? The error appears to indicate that there are no images available for processing.

Second, as with custom dataset, I am planning to set up a pipeline for custom real-world dataset.  The basic steps would include
1. Capture a sequence of images with a set-up similar to the one targeted in our paper, e.g. a circular arrangement of low-elevation input views and some deviated views positioned above the circle.
2. Use colmap or [hloc](https://github.com/cvg/Hierarchical-Localization) to estimate the camera pose.
2. Train a 3DGS using [gsplat](https://github.com/nerfstudio-project/gsplat). I suggest adapting [the training script](https://github.com/ChenYutongTHU/SplatFormer_DataGenerator/tree/1c20e0e8be250aa5ccaf51680ff4e84199c68d54#Train%203DGS) we used.
3. As our current model supports only object-centric scenes, the 3DGS produced in step 2 will need to be manually cropped to isolate the object. Alternatively, in step 2, you can use [sam2] (https://github.com/facebookresearch/sam2) to segment the capture sequences and train the 3DGS directly using segmented RGBA images.

4. Inputting the flawed 3DGS obtained by step-3 to the SplatFormer. 

As mentioned in the "Limitations and Future Work" section and Appendix F of our paper, our model is currently designed for setups where input views provide full coverage around one rotational axis (e.g., azimuth). This ensures that most parts of the objects are observed. Additionally, the model is limited to object-centric scenes, and addressing these constraints remains a focus for future development.

Thank you very much for bringing up this meaningful issue. I will add the discussed feature soon.

Best,
Yutong

**Comment by ryan-utopia** [comment]
First, there are no output images in the outputs/objaverse_splatformer/test/real directory, and I have checked that the real-world dataset is placed in test-set/realOOD. I think I need to do another check.

Second, thanks for your tips. I have added some code to export the 3DGS as `.ply` file after SplatFormer, this help me to explore the 3dGS more efficiently. Regarding the object-centric limitations, I also plan to do more testing on SplatFormer soon, as our goal is to reconstruct real scenes. Do you have any suggestions for improving SplatFormer to handle this?

**Comment by ChenYutongTHU** [comment]
Hi,

Thanks for another check. The real-world inference works for me.

As with future direction in unbounded scenes and real-world generalization, please refer to the section F. in our appendix for more details :)

Feel free to have more discussions. Thank you!

**Comment by ryan-utopia** [comment]
It works well when I comment the following code in `GS.py` (My environment is 8xRTX4090)

![image](https://github.com/user-attachments/assets/cedbbecc-df0b-439e-aba6-71ec5d6b7685)

**Comment by oUp2Uo** [comment]
Hi @ryan-utopia , could you please share some result images on real-world dataset?
Does it work well like synthetic datasets in the paper?
Thank you.

**Comment by ChenYutongTHU** [comment]
@ryan-utopia  I see. 
We need to use GPU=1 for inference, otherwise the data will be split.

**Comment by ryan-utopia** [comment]
@oUp2Uo I think it should work well if you have the same setting as the paper. And for other scenes, it seems to have the ability to remove some artifacts and gain some improvement.

**Comment by ryan-utopia** [comment]
@ChenYutongTHU yes, after adding `CUDA_VISIBLE_DEVICES=0`, it works well !
